- README.md
- package.json
Reverts s0ph1e/node-website-scraper#3
Remove coveralls.io support because of coveralls issues (https://github.com/lemurheavy/coveralls-public/issues/504 and https://github.com/lemurheavy/coveralls-public/issues/487)
> Revert "Add coveralls.io support"

- .travis.yml
Trying to fix `Error: Cannot find module` error
> Remove node_modules from travis cache

- lib/utils.js
- test/unit/utils-test.js
- When a resource link does not have a protocol defined the protocol from the url of the containing page should be used, instead of just choosing 'http'.
> Fixed bug with unspecified protocol in resources on https page.

- lib/file-handlers/css.js
- test/unit/file-handlers/css-test.js
> Fix similar css urls not updated

- lib/file-handlers/html.js
Promises should only be rejected with an Error. In this case there is no Error, but just no result.
Bluebird gives warnings when Promises are rejected without an Error.
> Fixed promise bug.

- lib/file-handlers/html.js
- lib/filename-generators/by-type.js
- lib/scraper.js
- package.json
- test/unit/file-handlers/html-test.js
- test/unit/file-name-generators/by-type-test.js
- test/unit/scraper-test.js
1. `requestResource` executes the request for the resource, and saves the response. Processing the same resource multiple times is prevented by maintaining `respondedResourcePromises`.
2. `loadResource` calls `requestResource` and saves the resource to disk. Processing the same resource multiple times is prevented by maintaining `loadedResourcePromises`.
3. To prevent deadlocks `file-handlers/html.js` only waits for `requestResource`, not for `loadResource`.
4. To determine when the scraper is finished `loadedResourcePromises` is used.
> Improved mechanism for re-using already loaded / loading resources.

- lib/config/resource-extensions-by-type.js
- lib/filename-generator/by-site-structure.js
- lib/filename-generator/by-type.js
- lib/utils.js
- test/unit/filename-generator/by-site-structure-test.js
- test/unit/utils-test.js
`getFilepathFromUrl` returns path which contains trailing slash, for example **/path/to/file/**
if html-file has no extension - [filename generator adds default filename](https://github.com/s0ph1e/node-website-scraper/blob/a56b963defac1c4b9d49409cb65a96c2e34dd3ed/lib/filename-generator/by-site-structure.js#L12) (**index.html**) to received path, so filepath will be **/path/to/file/index.html**
Bug #140 reproduces if there are both email and trailing slash in url (f.e. **/users/test@example.com/**):
* email contains **.com** which is recognized as extension -> so default filename is **NOT** added to filepath and it remains as in url (**/users/test@example.com/**)
* FS tries to save file **/users/test@example.com/** but it thinks that **test@example.com** should be directory because of …
> Fix incorrect filepath from url, fixes #140

- lib/utils.js
- test/unit/filename-generator/by-site-structure-test.js
- test/unit/filename-generator/by-type-test.js
- test/unit/utils-test.js
Filenames like `logo%20(1).svg` -> `logo (1).svg`
> Decode url-based filenames

- lib/scraper.js
- test/unit/scraper-test.js
Responded resource may be `null` due to request error, `urlFilter` or `maxDepth` options or if it was loaded earlier
> Call loadResource only for responded resources

- .eslintrc.yml
- lib/filename-generator/by-type.js
- lib/resource-handler/index.js
- lib/scraper.js
- lib/utils/index.js
- lib/utils/normalized-url-map.js
- test/unit/resource-handler/index.test.js
- test/unit/scraper-test.js
- test/unit/utils/normalized-url-map-test.js
- test/unit/utils/utils-test.js
* Use `NormalizedUrlMap` instead of plain objects in scraper (remove code duplicates)
* Call `loadResource` inside `requestResource` (remove manual calling in `load` method and in `ResourceHandler`)
* Split `requestResource` into 2 functions
> Refactor code duplicates, call loadResource inside requestResource

- lib/scraper.js
- lib/utils/index.js
- test/unit/filename-generator/by-type-test.js
- test/unit/scraper-init-test.js
> Fix ignoring different string cases in extensions

- README.md
- index.js
- lib/scraper.js
- test/unit/scraper-test.js
> Export default options

- lib/resource-handler/html/html-source-element.js
- lib/resource-handler/html/index.js
- test/unit/resource-handler/html.test.js
> Remove SRI check for loaded resources

- lib/config/defaults.js
Example tag: `<source src="file.mp4" type="video/mp4">` .
Instead of having the videos in the root folder, a `media` folder seems better.
> Add .mp4 files to a directory

- lib/utils/index.js
- test/functional/redirect/mocks/relative-resources-about.html
- test/functional/redirect/mocks/relative-resources-index.html
- test/functional/redirect/redirect.test.js
- test/unit/utils/utils-test.js
If we link to `http://example.com/about` which redirects to `http://example.com/about/` then relative resource url is incorrect because it is calculated using 1st url (`/about`), but should use updated url (`/about/`)
> Fix relative resources in redirected page

- lib/resource-handler/index.js
- lib/utils/index.js
- test/unit/resource-handler/index.test.js
- test/unit/utils/utils-test.js
* when filenameGenerator returns a path like `/a/css?family=Open+Sans:300,400,600,700&lang=en`,
it is escaped as `/a/css%3Ffamily%3DOpen%2BSans%3A300%2C400%2C600%2C700%26lang%3Den`
* also improved behavior of prettifyUrls
> escape newPath

- README.md
- lib/config/defaults.js
- lib/resource-handler/index.js
- test/functional/recursive/mocks/data.html
- test/functional/recursive/mocks/index.html
- test/functional/recursive/recursive.test.js
> Update links option

- lib/scraper.js
After storing some metadata from the afterResponse handler it should be possible to use that metadata when generating the filename
> Expose response data to generateFilename plugin event

- lib/config/defaults.js
Add rule to find resources from tags like `<tagname background = "Image URL"...>`
The background attribute deprecated in HTML5 but still may be used in old websites
Relates to https://github.com/website-scraper/website-scraper-puppeteer/issues/16
> Add background attribute to default sources

- lib/filename-generator/by-site-structure.js
- test/unit/filename-generator/by-site-structure-test.js
Fixes https://github.com/website-scraper/node-website-scraper/issues/411
When encountering a resource with query strings, the `generateFilename` of `by-site-structure.js` will:  
- convert `html` resources as `http://example.com/path?q=test => path/q=test.html`
- convert other resources like images by replacing `?` to `_`  since file system does not allow `?` as `http://example.com/path/picture.png?q=test => path/picture_q=test.png`
> Add workaround to scrape resources with query strings when using bySiteStructure

- lib/filename-generator/by-site-structure.js
- lib/filename-generator/by-type.js
- package-lock.json
- package.json
- test/unit/filename-generator/by-site-structure-test.js
- test/unit/filename-generator/by-type-test.js
Use sanitize-filename library as suggested in https://github.com/website-scraper/node-website-scraper/issues/413#issuecomment-688549499
Closes #413
> Use sanitizeFilaname in filename generators

- .codeclimate.yml
- .travis.yml
- appveyor.yml
- lib/scraper.js
- package-lock.json
- package.json
- test/functional/data-url/data-url.test.js
- test/functional/data-url/expected/index.html
- test/functional/data-url/mocks/index.html
> Release v5.0.0

- README.md
- lib/config/defaults.js
- lib/plugins/save-resource-to-fs-plugin.js
- lib/request.js
- lib/resource.js
- lib/scraper.js
- test/functional/encoding/hieroglyphs.test.js
- test/functional/encoding/mocks/index.html
- test/unit/request-test.js
- test/unit/scraper-init-test.js
- test/unit/scraper-test.js
This closes #454 and works in a nice generic way by passing through an encoding param which is used to save the file. This required some changes to the `afterResponse` API to allow it to work correctly however via `normalizeResponse` it will retain compatibility. Now I just need to fix-up the tests
> fix: non-english char encoding

- lib/plugins/generate-filenamy-by-site-structure-plugin.js
- lib/plugins/generate-filenamy-by-type-plugin.js
- lib/plugins/get-relative-path-reference-plugin.js
- lib/plugins/save-resource-to-fs-plugin.js
This PR aims to refactor the core library plugins to make them more extendable without changing any of the functional implementation.
Currently, though the plugins are exposed, they are not really extendable / modifiable. This PR aims to slightly address that issue
Currently the plugins rely on shared state through references to variables passed into closures. Moving the state of the plugin and closures to class properties and methods enables more adaptability for extending these plugins. For example
```js
import GenerateFilenameBySiteStructurePlugin from 'the/lib/path'
class MyCustomFileNamePlugins extends GenerateFilenameBySiteStructurePlugin {
generateFilename({resource}){
const {filename} = super.generateFilename({resource})
// Do custom stuff here
return {filename}
}
}
```
Any input …
> RFC: Refactor builtin plugins to expose class properties

- lib/plugins/generate-filenamy-by-site-structure-plugin.js
- lib/plugins/generate-filenamy-by-type-plugin.js
- lib/plugins/get-relative-path-reference-plugin.js
- lib/plugins/save-resource-to-fs-plugin.js
This reverts commit 5dde8ec21fdf234fa5abdf72dfb9ae4949f5ff0f.
It was decided to revert the changes (see [comment](https://github.com/website-scraper/node-website-scraper/pull/506#issuecomment-1243416683)) and remove plugins export (will be done in separate PR)
> Revert "RFC: Refactor builtin plugins to expose class properties (#506)"

- README.md
- package.json
- test/unit/scraper-test.js
Removing plugin exports as discussed in #510 
So that plugin code is not too tightly coupled to custom plugin implementations
Remove plugin exports and updated documentation 
Note: This should not be merged until V6
> #510 Remove plugin exports and update docs
