- README.md
- package.json
Reverts s0ph1e/node-website-scraper#7
Should be merged after coveralls.io issues (#7) will be resolved.
> Add coveralls.io support

- README.md
- index.js
- test/functional/base-test.js
- test/functional/recursive-test.js
- test/functional/resources-without-ext-test.js
> Export function instead of object. closes #23

- README.md
- index.js
- test/functional/base-test.js
- test/functional/recursive-test.js
- test/functional/resources-without-ext-test.js
Revert #24 (#23) due to #19.
Need to have separate methods for downloading and parsing
> Revert "Export function instead of object. closes #23"

- package.json
Sometimes travis builds are failing because of timeout
> Increment mocha timeout due to build failing

- lib/config/defaults.js
- lib/file-handlers/html.js
- lib/resource.js
- package.json
- test/unit/file-handlers/html-test.js
Cherry-pick of  #34 for future release [1.0.0](https://github.com/s0ph1e/node-website-scraper/milestones/v1.0.0)
> Fix loading from <img srcset="">

- lib/utils.js
- test/unit/utils-test.js
> Fixed bug with unspecified protocol in resources on https page (v0.3)

- README.md
- lib/scraper.js
- lib/utils.js
- test/functional/base-test.js
- test/unit/scraper-test.js
- test/unit/utils-test.js
> Remove createOutputObject and return resources as-is

- lib/filename-generators/by-site-structure.js
- lib/filename-generators/by-type.js
- lib/resource.js
- lib/utils.js
Nodejs 6 has [breaking change](https://github.com/nodejs/node/pull/5348/) in `path` module
> Fix exceptions in path.extname for node v6, close #70

- .eslintrc.yml
- README.md
- lib/config/defaults.js
- lib/scraper.js
- package.json
- test/unit/scraper-test.js
> Improve error handling 

- lib/filename-generators/by-site-structure.js
- lib/filename-generators/by-type.js
- lib/utils.js
- test/unit/file-name-generators/by-site-structure-test.js
- test/unit/file-name-generators/by-type-test.js
- test/unit/utils-test.js
> Fix long filenames handling

- README.md
- lib/logger.js
- lib/scraper.js
- lib/utils.js
> Log main events, closes #80

- lib/resource-handler/html.js
- lib/utils.js
- test/unit/resource-handler/html.test.js
- test/unit/utils-test.js
> Handle not supported URI schema, close #143

- package.json
> chore(package): update debug to version 2.4.5 (#159)

- lib/config/defaults.js
- lib/resource-handler/html/html-source-element.js
> Add picture srcset attr and .webp images support, close #179

- LICENSE
- package.json
- update years
- update lastname
- update package.json author
> Update LICENSE and package.json

- README.md
- lib/config/defaults.js
- lib/scraper.js
- test/functional/callbacks/callbacks.test.js
* add `onResourceSaved` callback - called when Resource was saved to fs
* add `onResourceError` callback - called when Resource's downloading/handling/saving was failed
> Add saved and error callbacks

- README.md
- package.json
> Fix URLs after moving repo to new organization

- .travis.yml
- appveyor.yml
> Update travis configuration to test on nodejs v9 and v10

- package.json
> fix(package): update fs-extra to version 8.0.1

- README.md
It took me a bit too long to figure this out, so thought I'd share.
> Update readme to fix server rejection

- README.md
Some small fixes in code style on README.
> Small fixes in code style

- package.json
> chore(package): update sinon to version 8.1.0

- .github/workflows/codeql-analysis.yml
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code
> Enable CodeQL configuration

- package-lock.json
- package.json
It's no longer used after we migrated from coveralls to codeclimate
> Remove coveralls

- .github/workflows/node.js.yml
Fix codeclimate build.
As we already have integration with it need to fix CI pipeline to upload coverage.
> Publish codeclimate coverage

- lib/config/defaults.js
- lib/plugins/save-resource-to-fs-plugin.js
- lib/request.js
- lib/scraper.js
- test/functional/encoding/hieroglyphs.test.js
- test/unit/scraper-init-test.js
Reverting #482 because of bugs https://github.com/website-scraper/node-website-scraper/issues/493 and failed tests in website-scraper-puppeteer plugin
Reopening previously closed issues #454 #466
I'll try to do another fix in next major version
> Revert encoding changes

- lib/config/defaults.js
Fixes bug #512 which was introduced in #445
> Fix ENOENT when running from working directory without package.json

- .github/workflows/node.js.yml
- README.md
> Use Qlty instead of Code Climate
